// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AFSTool")>]
[<assembly: AssemblyProductAttribute("SegaAFSTools")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-10-01T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","5b55884b7afb8b371a5d142e1ef9f9b461f17f15")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AFSTool"
    let [<Literal>] AssemblyProduct = "SegaAFSTools"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-10-01T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "5b55884b7afb8b371a5d142e1ef9f9b461f17f15"
