// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SegaAFSTools")>]
[<assembly: AssemblyProductAttribute("SegaAFSTools")>]
[<assembly: AssemblyDescriptionAttribute("Tools for working with AFS archive files, as appearing in games by and for Sega")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SegaAFSTools"
    let [<Literal>] AssemblyProduct = "SegaAFSTools"
    let [<Literal>] AssemblyDescription = "Tools for working with AFS archive files, as appearing in games by and for Sega"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
